//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sernasis.SernaSotomayor.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExploracionFisica
    {
        public int IdHistoria { get; set; }
        public string TA { get; set; }
        public Nullable<int> Pulso { get; set; }
        public Nullable<int> FR { get; set; }
        public Nullable<int> FC { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<int> Estatura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Texto { get; set; }
    }
}
