//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sernasis.SernaSotomayor.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicacionActual
    {
        public int Id { get; set; }
        public int IdHistoria { get; set; }
        public string Medicamento { get; set; }
        public string Dosis { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica { get; set; }
    }
}
