//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sernasis.SernaSotomayor.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoEspecialidad
    {
        public int Id { get; set; }
        public int IdMedico { get; set; }
        public string Cedula { get; set; }
        public int IdEspecialidad { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
