//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sernasis.SernaSotomayor.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UMSernaSotomayorEntities : DbContext
    {
        public UMSernaSotomayorEntities()
            : base("name=UMSernaSotomayorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<PersonaCatalogo> PersonaCatalogoes { get; set; }
        public virtual DbSet<PersonaLugare> PersonaLugares { get; set; }
        public virtual DbSet<PersonaTelefono> PersonaTelefonos { get; set; }
        public virtual DbSet<Catalogo> Catalogoes { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
        public virtual DbSet<Ubicacion> Ubicacions { get; set; }
        public virtual DbSet<Adiccione> Adicciones { get; set; }
        public virtual DbSet<Alergia> Alergias { get; set; }
        public virtual DbSet<AntecedentesHereditario> AntecedentesHereditarios { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<AntecedentesPersonalesPatológicos> AntecedentesPersonalesPatológicos { get; set; }
        public virtual DbSet<AntecedentesGinecoObstetricio> AntecedentesGinecoObstetricios { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinicas { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
        public virtual DbSet<AntecedentesGinecoObstetricio1> AntecedentesGinecoObstetricio1 { get; set; }
        public virtual DbSet<InterrogatorioAparatosSistema> InterrogatorioAparatosSistemas { get; set; }
        public virtual DbSet<MedicacionActual> MedicacionActuals { get; set; }
        public virtual DbSet<MedicoEspecialidad> MedicoEspecialidads { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<ExploracionFisica> ExploracionFisicas { get; set; }
        public virtual DbSet<NotaEvolutiva> NotaEvolutivas { get; set; }
    }
}
